### ISSUE TITLE
[Questuin] コンソールに表示されるステップ数について

### ISSUE THREAD

**Issue by za-wa-n-go** [kohya-ss/ControlNet-LLLite-ComfyUI#3]
<img width="412" alt="image" src="https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI/assets/118154415/5ecc3feb-f37a-4973-bd49-a1edee2672a1">

このような場合Step数はどのくらい機能しているのでしょうか。
KsamlerAdvanceを使って生成途中で別のKsamlerAdvanceに繋ぐといった複雑なワークフローを組んでいますが、一応総ステップ数は27なので27を入力していますが、11％しか適用していない雰囲気なので。
Step数を減らすと100％になるようですが、合っているのか分からず。

**Comment by za-wa-n-go** [comment]
LLLiteのsteps数を変えても結果に変化が無いので自分の構成だと効いていないかもしれません。
start/endは変化があります。
仕様を理解しきれていなそうです。

**Comment by kohya-ss** [comment]
コンソールには、適用開始時に`start LLLite: step 0`、終了時に`end LLLite: step 20`のように表示されます。この場合は、ステップ0から19に適用されています。

お書きいただいた例では`end`の表示がないので、全ステップに適用されていると思われます。

LLLiteのノードが認識するステップ数ですが、単純にU-Netが呼び出される回数になります。ですので、たとえば1ステップで2回呼び出すサンプラーを使うと二倍になります。

（ComfyUIの仕様でノードからは現在のステップ数が分からないので、呼び出された回数をカウントする仕様になっています。）

ノードの認識しているステップ数のリセットは、このノードが呼び出されたとき、および指定した回数だけステップが経過したとき（＝U-Netが指定回数だけ呼ばれたとき）に行われます。

以上、参考になれば幸いです。

**Comment by za-wa-n-go** [comment]
ありがとうございます！
